table Sales
	lineageTag: 16fa140c-43b3-4c14-a8be-e77c07de2ac8

	column SalesOrderLineKey
		dataType: int64
		formatString: 0
		lineageTag: b38549a0-b521-46e9-a454-46f9ede5901c
		summarizeBy: count
		sourceColumn: SalesOrderLineKey

		annotation SummarizationSetBy = Automatic

	column ResellerKey
		dataType: int64
		formatString: 0
		lineageTag: c7fcb72f-d708-4c2b-8379-8245f7b5dca8
		summarizeBy: count
		sourceColumn: ResellerKey

		annotation SummarizationSetBy = Automatic

	column CustomerKey
		dataType: int64
		formatString: 0
		lineageTag: 5637c180-90e7-42db-9f3a-8e2c48d0b7c3
		summarizeBy: count
		sourceColumn: CustomerKey

		annotation SummarizationSetBy = Automatic

	column ProductKey
		dataType: int64
		formatString: 0
		lineageTag: 676af70a-982c-40a9-948c-c2261888ef0d
		summarizeBy: count
		sourceColumn: ProductKey

		annotation SummarizationSetBy = Automatic

	column OrderDateKey
		dataType: int64
		formatString: 0
		lineageTag: 22335ad8-f193-4582-ba24-8ea825c94579
		summarizeBy: count
		sourceColumn: OrderDateKey

		annotation SummarizationSetBy = Automatic

	column DueDateKey
		dataType: int64
		formatString: 0
		lineageTag: ab02738f-1a05-4390-9d0a-88c469089a93
		summarizeBy: count
		sourceColumn: DueDateKey

		annotation SummarizationSetBy = Automatic

	column ShipDateKey
		dataType: int64
		formatString: 0
		lineageTag: 8ffc005c-4530-4c7d-ac6e-61fd12dc1e4c
		summarizeBy: count
		sourceColumn: ShipDateKey

		annotation SummarizationSetBy = Automatic

	column SalesTerritoryKey
		dataType: int64
		formatString: 0
		lineageTag: 4c5aba81-0ce9-45a6-a20c-3f34fb45d622
		summarizeBy: count
		sourceColumn: SalesTerritoryKey

		annotation SummarizationSetBy = Automatic

	column 'Order Quantity'
		dataType: int64
		formatString: 0
		lineageTag: 01d18d5e-bcb6-4eb2-bf70-8f9c31101146
		summarizeBy: sum
		sourceColumn: Order Quantity

		annotation SummarizationSetBy = Automatic

	column 'Unit Price'
		dataType: double
		lineageTag: 090e7c63-e85c-4c91-872f-206855ed7fb6
		summarizeBy: sum
		sourceColumn: Unit Price

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Extended Amount'
		dataType: double
		lineageTag: 63636d5e-ac40-4d52-a798-8623547dcdba
		summarizeBy: sum
		sourceColumn: Extended Amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Unit Price Discount Pct'
		dataType: int64
		formatString: 0
		lineageTag: 0fea6527-6e80-4765-8afb-7da91b38da28
		summarizeBy: sum
		sourceColumn: Unit Price Discount Pct

		annotation SummarizationSetBy = Automatic

	column 'Product Standard Cost'
		dataType: double
		lineageTag: ff114c1e-804e-4797-92c8-9f984431a850
		summarizeBy: sum
		sourceColumn: Product Standard Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Total Product Cost'
		dataType: double
		lineageTag: 196902c7-8bcf-45ec-b582-ac1b3db2878c
		summarizeBy: sum
		sourceColumn: Total Product Cost

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Sales Amount'
		dataType: double
		lineageTag: 81327362-d7eb-4dd3-b8aa-fe9b3570624c
		summarizeBy: sum
		sourceColumn: Sales Amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Sales = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://fiftyfivetechio.sharepoint.com/sites/mysite/Shared%20Documents/AdventureWorks%20Sales.xlsx"), null, true),
				    Sales_Table = Source{[Item="Sales",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Sales_Table,{{"SalesOrderLineKey", Int64.Type}, {"ResellerKey", Int64.Type}, {"CustomerKey", Int64.Type}, {"ProductKey", Int64.Type}, {"OrderDateKey", Int64.Type}, {"DueDateKey", Int64.Type}, {"ShipDateKey", Int64.Type}, {"SalesTerritoryKey", Int64.Type}, {"Order Quantity", Int64.Type}, {"Unit Price", type number}, {"Extended Amount", type number}, {"Unit Price Discount Pct", Int64.Type}, {"Product Standard Cost", type number}, {"Total Product Cost", type number}, {"Sales Amount", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

